ATTENDANCE_STATUS_PRESENT = "present"
ATTENDANCE_STATUS_ABSENT = "absent"
ATTENDANCE_STATUS_LATE = "late"
ATTENDANCE_STATUS_ON_LEAVE = "on_leave"

LATE_ARRIVAL_THRESHOLD_MINUTES = 15

JWT_TOKEN_PREFIX = "Bearer"

NOTIFICATION_EMAIL_SUBJECT_LATE = "Late Arrival Notification"
NOTIFICATION_EMAIL_SUBJECT_ABSENT = "Absence Notification"

GDPR_DATA_RETENTION_DAYS = 365
NEW_VARIABLE = 3456